spring:
  datasource:
    url: "jdbc:${DATABASE_URL}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.example.board: INFO
